create table "public"."meal_plans" (
    "id" bigint generated by default as identity not null,
    "start_date" date not null,
    "end_date" date not null,
    "created_at" timestamp with time zone not null,
    "created_by" uuid not null,
    "updated_at" timestamp with time zone
);


create table "public"."meal_plans-meals" (
    "id" bigint generated by default as identity not null,
    "meal_date" date not null,
    "fk_meal" bigint not null,
    "fk_meal_plan" bigint not null,
    "created_at" timestamp with time zone not null,
    "created_by" uuid not null,
    "updated_at" timestamp with time zone
);


CREATE UNIQUE INDEX "meal_plans-meals_pkey" ON public."meal_plans-meals" USING btree (id);

CREATE UNIQUE INDEX meal_plans_pkey ON public.meal_plans USING btree (id);

alter table "public"."meal_plans" add constraint "meal_plans_pkey" PRIMARY KEY using index "meal_plans_pkey";

alter table "public"."meal_plans-meals" add constraint "meal_plans-meals_pkey" PRIMARY KEY using index "meal_plans-meals_pkey";

alter table "public"."meal_plans" add constraint "meal_plans_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."meal_plans" validate constraint "meal_plans_created_by_fkey";

alter table "public"."meal_plans-meals" add constraint "meal_plans-meals_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."meal_plans-meals" validate constraint "meal_plans-meals_created_by_fkey";

alter table "public"."meal_plans-meals" add constraint "meal_plans-meals_fk_meal_fkey" FOREIGN KEY (fk_meal) REFERENCES meals(id) not valid;

alter table "public"."meal_plans-meals" validate constraint "meal_plans-meals_fk_meal_fkey";

alter table "public"."meal_plans-meals" add constraint "meal_plans-meals_fk_meal_plan_fkey" FOREIGN KEY (fk_meal_plan) REFERENCES meal_plans(id) not valid;

alter table "public"."meal_plans-meals" validate constraint "meal_plans-meals_fk_meal_plan_fkey";

grant delete on table "public"."meal_plans" to "anon";

grant insert on table "public"."meal_plans" to "anon";

grant references on table "public"."meal_plans" to "anon";

grant select on table "public"."meal_plans" to "anon";

grant trigger on table "public"."meal_plans" to "anon";

grant truncate on table "public"."meal_plans" to "anon";

grant update on table "public"."meal_plans" to "anon";

grant delete on table "public"."meal_plans" to "authenticated";

grant insert on table "public"."meal_plans" to "authenticated";

grant references on table "public"."meal_plans" to "authenticated";

grant select on table "public"."meal_plans" to "authenticated";

grant trigger on table "public"."meal_plans" to "authenticated";

grant truncate on table "public"."meal_plans" to "authenticated";

grant update on table "public"."meal_plans" to "authenticated";

grant delete on table "public"."meal_plans" to "service_role";

grant insert on table "public"."meal_plans" to "service_role";

grant references on table "public"."meal_plans" to "service_role";

grant select on table "public"."meal_plans" to "service_role";

grant trigger on table "public"."meal_plans" to "service_role";

grant truncate on table "public"."meal_plans" to "service_role";

grant update on table "public"."meal_plans" to "service_role";

grant delete on table "public"."meal_plans-meals" to "anon";

grant insert on table "public"."meal_plans-meals" to "anon";

grant references on table "public"."meal_plans-meals" to "anon";

grant select on table "public"."meal_plans-meals" to "anon";

grant trigger on table "public"."meal_plans-meals" to "anon";

grant truncate on table "public"."meal_plans-meals" to "anon";

grant update on table "public"."meal_plans-meals" to "anon";

grant delete on table "public"."meal_plans-meals" to "authenticated";

grant insert on table "public"."meal_plans-meals" to "authenticated";

grant references on table "public"."meal_plans-meals" to "authenticated";

grant select on table "public"."meal_plans-meals" to "authenticated";

grant trigger on table "public"."meal_plans-meals" to "authenticated";

grant truncate on table "public"."meal_plans-meals" to "authenticated";

grant update on table "public"."meal_plans-meals" to "authenticated";

grant delete on table "public"."meal_plans-meals" to "service_role";

grant insert on table "public"."meal_plans-meals" to "service_role";

grant references on table "public"."meal_plans-meals" to "service_role";

grant select on table "public"."meal_plans-meals" to "service_role";

grant trigger on table "public"."meal_plans-meals" to "service_role";

grant truncate on table "public"."meal_plans-meals" to "service_role";

grant update on table "public"."meal_plans-meals" to "service_role";


