create table "public"."grocery_items" (
    "id" bigint generated by default as identity not null,
    "created_by" uuid not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone,
    "is_picked" boolean not null,
    "name" text not null,
    "amount" text
);


alter table "public"."grocery_items" enable row level security;

CREATE UNIQUE INDEX grocery_lists_pkey ON public.grocery_items USING btree (id);

alter table "public"."grocery_items" add constraint "grocery_lists_pkey" PRIMARY KEY using index "grocery_lists_pkey";

alter table "public"."grocery_items" add constraint "grocery_items_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."grocery_items" validate constraint "grocery_items_created_by_fkey";

grant delete on table "public"."grocery_items" to "anon";

grant insert on table "public"."grocery_items" to "anon";

grant references on table "public"."grocery_items" to "anon";

grant select on table "public"."grocery_items" to "anon";

grant trigger on table "public"."grocery_items" to "anon";

grant truncate on table "public"."grocery_items" to "anon";

grant update on table "public"."grocery_items" to "anon";

grant delete on table "public"."grocery_items" to "authenticated";

grant insert on table "public"."grocery_items" to "authenticated";

grant references on table "public"."grocery_items" to "authenticated";

grant select on table "public"."grocery_items" to "authenticated";

grant trigger on table "public"."grocery_items" to "authenticated";

grant truncate on table "public"."grocery_items" to "authenticated";

grant update on table "public"."grocery_items" to "authenticated";

grant delete on table "public"."grocery_items" to "service_role";

grant insert on table "public"."grocery_items" to "service_role";

grant references on table "public"."grocery_items" to "service_role";

grant select on table "public"."grocery_items" to "service_role";

grant trigger on table "public"."grocery_items" to "service_role";

grant truncate on table "public"."grocery_items" to "service_role";

grant update on table "public"."grocery_items" to "service_role";

create policy "Delete based on userid"
on "public"."grocery_items"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = created_by));


create policy "Insert baed on userid"
on "public"."grocery_items"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = created_by));


create policy "Select based on userid"
on "public"."grocery_items"
as permissive
for select
to public
using ((( SELECT auth.uid() AS uid) = created_by));


create policy "Updated based on userid"
on "public"."grocery_items"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = created_by))
with check ((( SELECT auth.uid() AS uid) = created_by));



