create table "public"."ingredients" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "amount" text,
    "created_by" uuid not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone,
    "fk_meal" bigint not null
);


create table "public"."meals" (
    "id" bigint generated by default as identity not null,
    "description" text,
    "created_by" uuid not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone
);


CREATE UNIQUE INDEX ingredients_pkey ON public.ingredients USING btree (id);

CREATE UNIQUE INDEX meals_pkey ON public.meals USING btree (id);

alter table "public"."ingredients" add constraint "ingredients_pkey" PRIMARY KEY using index "ingredients_pkey";

alter table "public"."meals" add constraint "meals_pkey" PRIMARY KEY using index "meals_pkey";

alter table "public"."ingredients" add constraint "ingredients_fk_meal_fkey" FOREIGN KEY (fk_meal) REFERENCES meals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."ingredients" validate constraint "ingredients_fk_meal_fkey";

grant delete on table "public"."ingredients" to "anon";

grant insert on table "public"."ingredients" to "anon";

grant references on table "public"."ingredients" to "anon";

grant select on table "public"."ingredients" to "anon";

grant trigger on table "public"."ingredients" to "anon";

grant truncate on table "public"."ingredients" to "anon";

grant update on table "public"."ingredients" to "anon";

grant delete on table "public"."ingredients" to "authenticated";

grant insert on table "public"."ingredients" to "authenticated";

grant references on table "public"."ingredients" to "authenticated";

grant select on table "public"."ingredients" to "authenticated";

grant trigger on table "public"."ingredients" to "authenticated";

grant truncate on table "public"."ingredients" to "authenticated";

grant update on table "public"."ingredients" to "authenticated";

grant delete on table "public"."ingredients" to "service_role";

grant insert on table "public"."ingredients" to "service_role";

grant references on table "public"."ingredients" to "service_role";

grant select on table "public"."ingredients" to "service_role";

grant trigger on table "public"."ingredients" to "service_role";

grant truncate on table "public"."ingredients" to "service_role";

grant update on table "public"."ingredients" to "service_role";

grant delete on table "public"."meals" to "anon";

grant insert on table "public"."meals" to "anon";

grant references on table "public"."meals" to "anon";

grant select on table "public"."meals" to "anon";

grant trigger on table "public"."meals" to "anon";

grant truncate on table "public"."meals" to "anon";

grant update on table "public"."meals" to "anon";

grant delete on table "public"."meals" to "authenticated";

grant insert on table "public"."meals" to "authenticated";

grant references on table "public"."meals" to "authenticated";

grant select on table "public"."meals" to "authenticated";

grant trigger on table "public"."meals" to "authenticated";

grant truncate on table "public"."meals" to "authenticated";

grant update on table "public"."meals" to "authenticated";

grant delete on table "public"."meals" to "service_role";

grant insert on table "public"."meals" to "service_role";

grant references on table "public"."meals" to "service_role";

grant select on table "public"."meals" to "service_role";

grant trigger on table "public"."meals" to "service_role";

grant truncate on table "public"."meals" to "service_role";

grant update on table "public"."meals" to "service_role";


